# Generated by Django 3.0.4 on 2020-05-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Post image', upload_to='post_image/', verbose_name='Post image:')),
                ('title', models.CharField(help_text='Input post title', max_length=200, verbose_name='Post title:')),
                ('about', models.TextField(help_text='Text of post', verbose_name='About text:')),
            ],
        ),
    ]
